# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "hashicorp/precise32"

  config.vm.network :forwarded_port, guest: 8000, host: 8000

  config.vm.synced_folder "..", "/home/vagrant/site"

  config.vm.provision :shell, :path => "bootstrap.sh"
end
